apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    pipeline.openshift.io/started-by: opentlc-mgr
  generateName: maven-demo-app-
  namespace: demo
  labels:
    tekton.dev/pipeline: maven-demo-app
spec:
  pipelineRef:
    name: maven-demo-app
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: scratchpad
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
          volumeMode: Filesystem