kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: websphere-traditional
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 'prod'
      from:
        kind: DockerImage
        name: 'ibmcom/websphere-traditional:8.5.5.20'