kind: ImageStreamTag
apiVersion: image.openshift.io/v1
metadata:
  name: 'websphere-traditional:8.5.5.20'
tag:
  name: '8.5.5.20'
  from:
    kind: DockerImage
    name: 'ibmcom/websphere-traditional:'
  generation: 2
  importPolicy: {}
  referencePolicy:
    type: Local
lookupPolicy:
  local: false
---
kind: ImageStreamTag
apiVersion: image.openshift.io/v1
metadata:
  name: 'websphere-traditional:9.0.5.10'
tag:
  name: '8.5.5.20'
  from:
    kind: DockerImage
    name: 'ibmcom/websphere-traditional:9.0.5.10'
  generation: 2
  importPolicy: {}
  referencePolicy:
    type: Local
lookupPolicy:
  local: false
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: import-websphere-traditional
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'websphere-traditional:prod'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: 'websphere-traditional:8.5.5.20'
  postCommit: {}
  source:
    type: Dockerfile
    dockerfile: FROM whatever
  triggers:
    - type: ImageChange
    - type: ConfigChange
  runPolicy: Serial