apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  name: maven-demo-app-war-app
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven-demo-app-war-app
      deploymentconfig: maven-demo-app-war-app
  template:
    metadata:
      labels:
        app: maven-demo-app-war-app
        deploymentconfig: maven-demo-app-war-app
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: maven-demo-app-war-app
          image: >-
            image-registry.openshift-image-registry.svc:5000/demo/maven-demo-app-war:latest
          ports:
            - containerPort: 9443
              protocol: TCP